name: MeaningAndroid Builder

on:
  push:
    branches: [ develop ]

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: On Failed, Notify in Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'nneaning/Anroid Debug build Fail❌'
          SLACK_COLOR: '#FF5733'
          MSG_MINIMAL: true
          SLACK_MESSAGE: '에러를 확인해주세요'

      - name: Upload APK
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs


  upload:
    needs: [build]
    name: upload to Slack
    runs-on: ubuntu-latest
    steps:        
      - name: download Article
        uses: actions/download-artifact@v2
        with:
          name: app/build/outputs  
          
      - name: Update Release apk name
        if: ${{ success() }}
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk 미닝-Debug.apk
          echo 'apk=미닝-Debug.apk' >> $GITHUB_ENV
          
      - name: Upload APK at Slack
        if: ${{ success() }}
        run: |
          curl -X POST \
          -F file=@$apk \
          -F channels=${{secrets.SLACK_CHANNEL_ID}} \
          -H "Authorization: Bearer ${{secrets.SLACK_BOT_TOKEN}}" \
          https://slack.com/api/files.upload
          
      - name: On Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'nneaning/Anroid Debug build Success✅'
          SLACK_COLOR: '#5BFF33'
          MSG_MINIMAL: true
          SLACK_MESSAGE: 'apk 생성 완료! '

      - name: On Success but Fail
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'nneaning/Anroid Debug build Success✅'
          SLACK_COLOR: '#FFF233'
          MSG_MINIMAL: true
          SLACK_MESSAGE: '빌드는 완료 되었으나 apk업로드 에러'
